// workflow/STATUS.md: an honest progress report regenerated on every referee save.
// It separates implemented / verified / deferred / blocked work and never turns task counts into a
// product-readiness percentage.

import { allTasks } from "./plan.mjs";

const VERIFICATION_LABELS = {
  reviewed_and_validated: "reviewed + checks passed on the reviewed code",
  acceptance_suite: "automated acceptance suite passed",
  human: "completed/verified by a person",
  review_only_pre_repair:
    "approved before the 2026-09 repair (review only; re-verified by later acceptance tasks)",
};

export function renderStatus(state, bp, history) {
  const tasks = allTasks(bp);
  const current = tasks.find((x) => x.task.id === state.current_task_id);
  const lines = [
    "# Autopilot status",
    "",
    `_Generated by the referee at ${state.updated_at ?? "unknown"}. Do not edit by hand._`,
    "",
    `**State:** ${state.status}${state.pause_reason ? ` — ${state.pause_reason}` : ""}`,
    `**Current task:** ${current ? `${current.task.id} ${current.task.title}` : "none"}`,
    `**Next action:** ${state.handoff_instructions}`,
    "",
  ];

  const v = state.last_validation;
  lines.push("## Most recent validation", "");
  if (!v) lines.push("None recorded yet.", "");
  else {
    lines.push(
      `${v.passed ? "Passed" : v.infra ? "Could not run (infrastructure)" : "Failed"} at ${v.at} (code fingerprint \`${String(v.fingerprint).slice(0, 12)}\`)`,
      "",
    );
    for (const r of v.results ?? [])
      lines.push(`- ${r.passed ? "✅" : r.classification === "infra" ? "⚠️" : "❌"} ${r.name}`);
    lines.push("");
  }

  if (state.review_notes || state.last_error) {
    lines.push("## Unresolved", "");
    if (state.review_notes)
      lines.push(`- Review/referee notes: ${state.review_notes.split("\n")[0].slice(0, 400)}`);
    if (state.last_error) lines.push(`- Last error: ${state.last_error.slice(0, 400)}`);
    lines.push("");
  }

  lines.push(
    "## Milestones",
    "",
    "| Milestone | Level | Automated acceptance | Open | Deferred (needs a person) |",
    "|---|---|---|---|---|",
  );
  for (const m of bp.milestones) {
    const open = m.tasks.filter((t) => t.status !== "done" && !t.deferred).length;
    const deferred = m.tasks.filter((t) => t.status !== "done" && t.deferred).map((t) => t.id);
    lines.push(
      `| ${m.key} ${m.name} | ${m.status} | ${m.automated_acceptance?.passed_at ? `passed ${m.automated_acceptance.passed_at.slice(0, 10)}` : "not yet"} | ${open} | ${deferred.join(", ") || "—"} |`,
    );
  }
  lines.push(
    "",
    "_Levels: in_progress → code_complete (all non-deferred tasks accepted) → accepted (all tasks, including human checks and the acceptance suite)._",
    "",
  );

  const section = (title, rows) => {
    lines.push(`## ${title}`, "");
    if (rows.length === 0) lines.push("None.", "");
    else lines.push(...rows, "");
  };
  section(
    "Blocked or waiting",
    tasks
      .filter((x) => x.task.status === "blocked" || (x.task.deferred && x.task.status !== "done"))
      .map(
        (x) =>
          `- ${x.task.id} ${x.task.title}${x.task.requires_human ? ` — needs a person: ${x.task.requires_human}` : ""}`,
      ),
  );
  section(
    "Accepted tasks by verification level",
    Object.entries(
      tasks
        .filter((x) => x.task.status === "done")
        .reduce((acc, x) => {
          const level = x.task.verification?.level ?? "review_only_pre_repair";
          (acc[level] ??= []).push(x.task.id);
          return acc;
        }, {}),
    ).map(
      ([level, ids]) =>
        `- **${VERIFICATION_LABELS[level] ?? level}** (${ids.length}): ${ids.join(", ")}`,
    ),
  );
  section(
    "Recent referee decisions",
    history
      .slice(-10)
      .reverse()
      .map(
        (h) =>
          `- ${h.at} ${h.task ?? ""} ${h.kind}: ${String(h.summary ?? h.decision ?? "").slice(0, 200)}`,
      ),
  );
  return lines.join("\n");
}
